package Favorites;

import Client.ClientLogger;
import Dialog.MessageDialog;
import java.io.*;
import java.util.Properties;


public class Servers {

    private final static String filename = "servers.ini";
    private static Properties props = new Properties();

    public static void addServer(String address) {
        String key = "server" + props.size();
        props.setProperty(key, address);
    }

    /**
     * Vycisti obsah objektu typu Properties.
     * Pouziva se pri novem vkladani hodnot pri ukladani souboru.
     */
    public static void reset() {
        props.clear();
    }

    public static String[] loadFile() {

        try (FileInputStream in = new FileInputStream(filename)) {
            props.load(in);
        } catch (FileNotFoundException e) {
            // Soubor jeste nebyl vytvoren.
        } catch (IOException e) {
            ClientLogger.log(e.getMessage(), ClientLogger.ERROR);
            MessageDialog.error("Chyba aplikace", "Konfigurační soubor není možné načíst.");
        }

        String[] array = props.values().toArray( new String[ props.size() ] );
        return array;

    }

    /**
     * Soubor se vytvari automaticky, pokud neexistuje.
     */
    public static void saveFile() {

        try (FileOutputStream out = new FileOutputStream(filename)) {
            props.store(out, "Server list. Generated by IRC client application.\nDo not modify by hand!");
        } catch (IOException e) {
            ClientLogger.log(e.getMessage(), ClientLogger.ERROR);
            MessageDialog.error("Chyba aplikace", "Konfigurační soubor není možné uložit.");
        }

    }

}
